/**
 * Generates new 0-level characters. See the README.md file for instructions.
 *
 * Syntax: !fodder
 */

/**
 * Configuration
 *
 * Configure these to match your actual table names or vice-versa.
 * RaceTable is optional (e.g. used in rolling Crawling Under A Broken Moon characters)
 * and must be uncommented to use.
 */
//var RaceTable = 'Races';
var OccupationTable = 'Occupations';
var LuckTable = 'Birth-Augur-Lucky-Roll';
var EquipmentTable = 'Equipment';
var DefaultAvatar = 'https://s3.amazonaws.com/files.d20.io/images/7165064/VtQt1TimmSc8rxdHH4daxg/med.jpg?1421350799';

var Fodder = Fodder || {};

on('chat:message', function(msg) {
    // Exit if not an api command
    if (msg.type != "api") {
        return;
    }

    if (msg.content.indexOf('!fodder') != -1) {
        Fodder.Generate(msg);
    }
});

Fodder.Generate = function(msg) {
        var player = msg.who;
        var name = msg.who + Date.now();
        var character = createObj('character', {
            avatar: defaultAvatar,
            name: name,
            bio: '',
            gmnotes: 'Player: '+player+'<br>Generated by script Fodderator.js',
            archived: false,
            inplayerjournals: 'all',
            controlledby: msg.playerid
        });
        var rollAbility = function() {
            return randomInteger(6) + randomInteger(6) + randomInteger(6);
        };
        var rollHP = function(staminaMod) {
            return randomInteger(4) + staminaMod;
        };
        var rollCoin = function() {
            return randomInteger(12) + randomInteger(12) + randomInteger(12) + randomInteger(12) + randomInteger(12);
        };
        var calcMod = function(ability) {
            return Math.floor( (0.0009 * ability * ability * ability) + (-0.029 * ability * ability) + (0.6 * ability) +0.41) -4;
        };

        if (typeof RaceTable != 'undefined') {
            var rollRace = function() {
                sendChat("API", "/roll 1t["+RaceTable+"]", function(result) {
                    var content = JSON.parse(result[0].content);
                    createObj('attribute', {
                        name: 'Race',
                        current: content.rolls[0].results[0].tableItem.name,
                        _characterid: character.id
                    });
                });
            }
        }

        if (typeof OccupationTable != 'undefined') {
            var rollOccupation = function() {
                sendChat("API", "/roll 1t["+OccupationTable+"]", function(result) {
                    var content = JSON.parse(result[0].content);
                    var values = content.rolls[0].results[0].tableItem.name.split(':');
                    createObj('attribute', {
                        name: 'Occupation',
                        current: values[0],
                        _characterid: character.id
                    });
                    if (typeof EquipmentTable != 'undefined') {
                        rollEquipment(values[1], values[2]);
                    }
                });
            };
        }

        if (typeof LuckTable != 'undefined') {
            var rollLuck = function () {
                sendChat("API", "/roll 1t[" + LuckTable + "]", function (result) {
                    var content = JSON.parse(result[0].content);
                    var values = content.rolls[0].results[0].tableItem.name.split(':');
                    createObj('attribute', {
                        name: 'BirthAugur',
                        current: values[0],
                        _characterid: character.id
                    });
                    createObj('attribute', {
                        name: 'LuckyRoll',
                        current: values[1],
                        _characterid: character.id
                    });
                });
            };
        }

        if (typeof EquipmentTable != 'undefined') {
            var rollEquipment = function (item_1, item_2) {
                sendChat("API", "/roll 1t[" + EquipmentTable + "]", function (result) {
                    var content = JSON.parse(result[0].content);
                    var item_3 = content.rolls[0].results[0].tableItem.name;
                    createObj('attribute', {
                        name: 'Equipment',
                        current: item_1 + "\n" + item_2 + "\n" + item_3,
                        _characterid: character.id
                    });
                });
            };
        }

        /* Roll abilities */
        var strength = rollAbility();
        var agility = rollAbility();
        var stamina = rollAbility();
        var personality = rollAbility();
        var intelligence = rollAbility();
        var luck = rollAbility();

        var staminaMod = calcMod(stamina);
        var hp = rollHP(staminaMod);
        var cp = rollCoin();

        /* Create attributes */
        createObj('attribute', {
            name: 'player_name',
            current: player,
            _characterid: character.id
        })
        createObj('attribute', {
            name: 'Name',
            current: name,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Languages',
            current: 'Common',
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Speed',
            current: 30,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Level',
            current: '0',
            max: '10',
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'XP',
            current: 0,
            max: 10,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Strength',
            current: strength,
            max: strength,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Agility',
            current: agility,
            max: agility,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Stamina',
            current: stamina,
            max: stamina,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Personality',
            current: personality,
            max: personality,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Intelligence',
            current: intelligence,
            max: intelligence,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Luck',
            current: luck,
            max: luck,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Luck_Starting',
            current: luck,
            max: luck,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'HP',
            current: hp,
            max: hp,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'CP',
            current: cp,
            _characterid: character.id
        });

        if (typeof LuckTable != 'undefined') {
            rollLuck();
        }
        if (typeof RaceTable != 'undefined') {
            rollRace();
        }
        if (typeof OccupationTable != 'undefined') {
            rollOccupation();
        }

        sendChat(player, "/me turned it up to 11 and summoned a character named \""+name+"\"!");
};
