/**
 * Permit all players to create new 0-level characters. Created characters will be
 * visible in all journals and controllable by the player who created it.
 *
 * Syntax: !fodder Character Name
 * `Character Name' has no limitations, and will be used for the character's
 * name in the journal.
 */
/*var Fodder = Fodder || {};*/

on('chat:message', function(msg) {
    if (msg.type == 'api' && msg.content.indexOf('!fodder ') != -1) {
        var name = msg.content.substring(8);
        var player = msg.who;
        var character = createObj('character', {
            avatar: 'https://s3.amazonaws.com/files.d20.io/images/7165064/VtQt1TimmSc8rxdHH4daxg/med.jpg?1421350799',
            name: name,
            bio: '',
            gmnotes: 'Player: '+player+'<br>Generated by script Fodderator.js',
            archived: false,
            inplayerjournals: 'all',
            controlledby: msg.playerid
        });
        var rollAbility = function() {
            return randomInteger(6) + randomInteger(6) + randomInteger(6);
        };
        var rollHP = function(staminaMod) {
            return randomInteger(4) + staminaMod;
        }
        var rollCoin = function() {
            return randomInteger(12) + randomInteger(12) + randomInteger(12) + randomInteger(12) + randomInteger(12);
        }
        var calcMod = function(ability) {
            return Math.floor( (0.0009 * ability * ability * ability) + (-0.029 * ability * ability) + (0.6 * ability) +0.41) -4;
        };
        var rollRace = function() {
            sendChat("API", "/roll 1t[Races]", function(result) {
                var content = JSON.parse(result[0].content);
                createObj('attribute', {
                    name: 'Race',
                    current: content.rolls[0].results[0].tableItem.name,
                    _characterid: character.id
                });
            });
        }
        var rollOccupation = function() {
            sendChat("API", "/roll 1t[Occupations]", function(result) {
                var content = JSON.parse(result[0].content);
                var values = content.rolls[0].results[0].tableItem.name.split(':');
                createObj('attribute', {
                    name: 'Occupation',
                    current: values[0],
                    _characterid: character.id
                });
                rollEquipment(values[1], values[2]);
            });
        }
        var rollLuck = function() {
            sendChat("API", "/roll 1t[Birth-Augur-Lucky-Roll]", function (result) {
                var content = JSON.parse(result[0].content);
                var values = content.rolls[0].results[0].tableItem.name.split(':');
                createObj('attribute', {
                    name: 'BirthAugur',
                    current: values[0],
                    _characterid: character.id
                });
                createObj('attribute', {
                    name: 'LuckyRoll',
                    current: values[1],
                    _characterid: character.id
                });
            });
        };
        var rollEquipment = function (item_1, item_2) {
            sendChat("API", "/roll 1t[Equipment]", function(result) {
                var content = JSON.parse(result[0].content);
                var item_3 = content.rolls[0].results[0].tableItem.name;
                createObj('attribute', {
                    name: 'Equipment',
                    current: item_1 + "\n" + item_2 + "\n" + item_3,
                    _characterid: character.id
                });
            });
        };

        /* Roll abilities */
        var strength = rollAbility();
        var agility = rollAbility();
        var stamina = rollAbility();
        var personality = rollAbility();
        var intelligence = rollAbility();
        var luck = rollAbility();

        var staminaMod = calcMod(stamina);
        var hp = rollHP(staminaMod);
        var cp = rollCoin();

        /* Create attributes */
        createObj('attribute', {
            name: 'player_name',
            current: player,
            _characterid: character.id
        })
        createObj('attribute', {
            name: 'Name',
            current: name,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Languages',
            current: 'Common',
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Speed',
            current: 30,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Level',
            current: '1',
            max: '10',
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'XP',
            current: 0,
            max: 10,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Strength',
            current: strength,
            max: strength,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Agility',
            current: agility,
            max: agility,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Stamina',
            current: stamina,
            max: stamina,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Personality',
            current: personality,
            max: personality,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Intelligence',
            current: intelligence,
            max: intelligence,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Luck',
            current: luck,
            max: luck,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'Luck_Starting',
            current: luck,
            max: luck,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'HP',
            current: hp,
            max: hp,
            _characterid: character.id
        });
        createObj('attribute', {
            name: 'CP',
            current: cp,
            _characterid: character.id
        });

        rollLuck();
        rollRace();
        rollOccupation();

        sendChat(player, "/me turned it up to 11 and summoned a character named \""+name+"\"!");
    }

});